#!/usr/bin/env bash
#
# Build tests for GD32F303RET6_creality
#

# exit on first failure
set -e

#
# Build with configs included in the PR
#
use_example_configs "Creality/Ender-5 Pro V2"
opt_enable MARLIN_DEV_MODE
exec_test $1 $2 "Ender 3 v2" "$3"

use_example_configs "Creality/Ender-5 Pro V2"
opt_disable CLASSIC_JERK
opt_add SDCARD_EEPROM_EMULATION
opt_set TEMP_SENSOR_BED 0
exec_test $1 $2 "Ender 3 v2, SD EEPROM, no CLASSIC_JERK, no Bed" "$3"

restore_configs
opt_set MOTHERBOARD BOARD_CREALITY_V422GD SERIAL_PORT 1 DGUS_LCD_UI IA_CREALITY
opt_enable NOZZLE_PARK_FEATURE ADVANCED_PAUSE_FEATURE LCD_BED_TRAMMING CLASSIC_JERK BABYSTEPPING \
           AUTO_BED_LEVELING_BILINEAR PROBE_MANUALLY FAN_SOFT_PWM
opt_add NO_CREALITY_422_DRIVER_WARNING
opt_add NO_AUTO_ASSIGN_WARNING
exec_test $1 $2 "Creality V4.2.2 with IA_CREALITY" "$3"

# clean up
restore_configs
